[package]
name = "mapdiffbot2"
version = "0.1.0"
edition = "2021"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.194", features = ["derive"] }
serde_json = { version = "1.0.110" }
toml = "0.8.8"
octocrab = "0.32.0"
dmm-tools = { git = "https://github.com/jupyterkat/SpacemanDMM/" }
dreammaker = { git = "https://github.com/jupyterkat/SpacemanDMM/" }
ahash = "0.8.7"
path-absolutize = "3.1.1"
jsonwebtoken = "9.2.0"
eyre = "0.6.11"
simple-eyre = "0.3.1"
rayon = "1.8.0"
image = "0.24.7"
diffbot_lib = { path = "../diffbot_lib" }
git2 = "0.18.1"
walkdir = "2.4.0"
delay_timer = "0.11.4"
itertools = "0.12.0"
indexmap = { version = "2.1.0", features = ["rayon"] }
tracing-loki = "0.2.4"
flume = "0.11.0"
object_store = { version = "0.8.0", features = ["azure"] }
mysql_async = "0.33.0"
time = "0.3.31"
secrecy = "0.8.0"

actix-web = "4.4.1"
actix-files = "0.6.2"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5.4"
