[workspace]
resolver = "2"
members = [
    "crates/diffbot_lib",
    "crates/icondiffbot2",
    "crates/icondiffbot_test_generator",
    "crates/mapdiffbot2",
]

[profile.release]
#lto = true
debug = true
