[package]
name = "icondiffbot2"
version = "0.1.0"
edition = "2021"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
octocrab = "0.32.0"
dmm-tools = { git = "https://github.com/jupyterkat/SpacemanDMM/" }
jsonwebtoken = "9.2.0"
reqwest = "0.11.23"
diffbot_lib = { path = "../diffbot_lib" }
eyre = "0.6.11"
simple-eyre = "0.3.1"
rayon = "1.8.0"
toml = "0.8.8"
ahash = "0.8.7"
hashbrown = { version = "0.14.3", features = ["rayon"] }
tracing-loki = "0.2.4"
flume = "0.11.0"
mysql_async = "0.33.0"
time = "0.3.31"
secrecy = "0.8.0"

actix-web = "4.4.1"
actix-files = "0.6.5"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5.4"

[dependencies.tracing]
version = "0.1.40"
features = ["attributes"]
