[package]
name = "diffbot_lib"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
serde = { version = "1.0.194", features = ["derive"] }
octocrab = "0.32.0"
eyre = "0.6.11"
derive_builder = "0.12.0"
chrono = "0.4.31"
sha2 = "0.10.8"
hmac = "0.12.1"
hex = "0.4.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "time"] }
tracing-panic = "0.1.1"
tracing-loki = "0.2.4"
flume = "0.11.0"
async-fs = "2.1.0"

actix-web = "4.4.1"
